
spring.profiles.include: customlog

io.jrevolt.sysmon.zabbix:
   reset: ${reset:false}
   configure: ${configure:true}
   threads: ${threads:24}
   clusterInclude: ${clusterInclude:.*}
   clusterExclude: ${clusterExclude:UNDEFINED}
   skipHosts: ${skipHosts:false}
   skipItems: ${skipItems:false}
   skipTriggers: ${skipTriggers:false}
   actionMessage:
      subject: >
         {TRIGGER.STATUS}: {TRIGGER.NAME}
      message: |
         Trigger : {TRIGGER.NAME}
         Status  : {TRIGGER.STATUS}
         Severity: {TRIGGER.SEVERITY}
         Host    : {HOST.NAME1}
         Item    : {ITEM.NAME1}
         Key     : {ITEM.KEY1}
         Value   : {ITEM.VALUE1}
         Event   : {EVENT.ID}
      recoverySubject: >
         {TRIGGER.STATUS}: {TRIGGER.NAME}
      recoveryMessage: |
         Trigger : {TRIGGER.NAME}
         Status  : {TRIGGER.STATUS}
         Severity: {TRIGGER.SEVERITY}
         Host    : {HOST.NAME1}
         Item    : {ITEM.NAME1}
         Key     : {ITEM.KEY1}
         Value   : {ITEM.VALUE1}
         Event   : {EVENT.ID}

---

spring.profiles: customlog
spring.main.show-banner: false
logging:
   pattern.console:  "%clr(%d{HH:mm:ss}){faint} %clr(%p){green} %clr(%t){blue} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%rEx}"
   pattern.file:     "%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ} %5p %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%rEx}"
   path:             "${user.home}/.io.jrevolt.sysmon"
   file:             "${logging.path}/zabbix.log"
   level:
      root: WARN
      io.jrevolt.sysmon: DEBUG
      com.zabbix4j: INFO
